"""Export INT8 weights + pre-scaled bias as a C header for the Nios V/m
software CNN (bench firmware). Layout matches the plain triple-loop conv in
cnn_sw.c: w[out][in][tap], row-major flattened.

Bias is pre-scaled into the accumulator domain exactly as the golden does:
  conv: b_acc = round(b_int8 * 2^nb[layer])   (INT32)
  fc:   b_acc = round(b_int8 * 2^w_shift[fc]) (INT32)

so the C code just adds b_acc into acc before the round-half-up shift.
"""

import os
import argparse
import numpy as np
import torch


def carr(name, arr, ctype):
    arr = np.asarray(arr).flatten()
    body = ",".join(str(int(v)) for v in arr)
    return f"static const {ctype} {name}[{arr.size}] = {{{body}}};\n"


def run(args):
    ckpt = torch.load(args.checkpoint, map_location='cpu', weights_only=False)
    w = {k: np.array(v, dtype=np.int64) for k, v in ckpt['w_int8'].items()}
    b = {k: np.array(v, dtype=np.float64) for k, v in ckpt['b_int8'].items()}
    nb = ckpt['nb']
    w_shift = ckpt['w_shift']

    def bias_acc(layer, shift):
        return np.round(b[layer] * (2.0 ** shift)).astype(np.int64)

    lines = [
        "// ecg_weights.h - AUTO-GENERATED by export_weights_niosv_c.py\n",
        "// INT8 weights [out][in][tap] + INT32 bias pre-scaled to acc domain.\n",
        "#ifndef ECG_WEIGHTS_H\n#define ECG_WEIGHTS_H\n\n",
    ]

    # nb / shift constants
    lines.append(f"#define NB_C1 {nb['conv1']}\n")
    lines.append(f"#define NB_C2 {nb['conv2']}\n")
    lines.append(f"#define NB_C3 {nb['conv3']}\n")
    lines.append(f"#define NB_C4 {nb['conv4']}\n")
    lines.append(f"#define SH_FC {w_shift['fc']}\n\n")

    for layer in ('conv1', 'conv2', 'conv3', 'conv4'):
        oc, ic, k = w[layer].shape
        lines.append(f"// {layer}: out={oc} in={ic} k={k}\n")
        lines.append(carr(f"w_{layer}", w[layer], "signed char"))
        n = nb[layer]
        lines.append(carr(f"b_{layer}", bias_acc(layer, n), "int"))
        lines.append("\n")

    # FC: w[out][in]
    oc, ic = w['fc'].shape
    lines.append(f"// fc: out={oc} in={ic}\n")
    lines.append(carr("w_fc", w['fc'], "signed char"))
    lines.append(carr("b_fc", bias_acc('fc', w_shift['fc']), "int"))
    lines.append("\n#endif\n")

    with open(args.output, 'w') as f:
        f.writelines(lines)
    print(f"[OK] wrote {args.output}")


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument('--checkpoint', default='./results/qat_int8/model_qat_int8.pth')
    p.add_argument('--output',
                   default='../../hardware/fpga/sw/niosv/ecg_weights.h')
    return p.parse_args()


if __name__ == "__main__":
    run(parse_args())
